default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  port: 5432
  username: 
  password:

development:
  <<: *default
  host: localhost
  database: sellbrite_test_development

test:
  <<: *default
  host: localhost
  database: sellbrite_test_test

production:
  <<: *default
  database: sellbrite_test_production
